spring.application.name=battle-backend
server.port=8088
# # 1. 擴大 Tomcat 處理請求的執行緒數量 (預設為 200，調高到 500 或 1000)
# server.tomcat.threads.max=1000
# # 最少保持活動的執行緒數 (避免流量突增時才臨時建立)
# server.tomcat.threads.min-spare=100

# # 2. 擴大最大連線數 (預設 8192，可視記憶體大小調高)
# server.tomcat.max-connections=20000

# # 3. 擴大 TCP 排隊等候佇列 (預設 100，當瞬間湧入過多連線，排不進來的就會直接被拒絕！調高到 1000)
# server.tomcat.accept-count=2000
